name: zayat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  http: ^1.1.0
  video_player: ^2.8.1
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  flutter_expandable_text: ^1.0.0
  chewie: ^1.7.4
  retrofit: ^4.0.3
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  pull_to_refresh: ^2.0.0
  google_mobile_ads: ^4.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  # flutter_local_notifications: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  retrofit_generator: ^8.0.5
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
